services:
  p2:
    build:
      context: .
      dockerfile: Dockerfile
    image: novocert-p2-1:compose-build
    container_name: novocert-p2-1
    volumes:
      - type: bind
        source: ../app/casanovo_config
        target: /app/output
