services:
  p4:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: novocert-p4:compose-build
    container_name: novocert-p4
    # user: "${UID:-1000}:${GID:-1000}"
    environment:
      - FDR_TYPE=peptide
      - FDR=0.01
    volumes:
      - type: bind
        source: ../app/3.Feature calculation/output/t_d.pin
        target: /app/t_d.pin
      - type: bind
        source: ../app/4.Percolator_FDRControl/output
        target: /app/output
