services:
  p1:
    build:
      context: .
      dockerfile: Dockerfile
    image: novocert-p1:compose-build
    container_name: novocert-p1
    environment:
      - MEMORY=8
      - PRECURSOR_TOLERANCE=16
      - RANDOM_SEED=32
    volumes:
      - type: bind
        source: ../app/1.Decoy_spectra_generation/sample
        target: /app/input
      - type: bind
        source: ../app/1.Decoy_spectra_generation/output
        target: /app/output
